"""Combo tools for Store API - high-level wrappers over erc3.store"""

from .dtos import (
    ErrorInfo,
    Combo_Find_Best_Combination_For_Products_And_Coupons,
    Resp_Combo_Find_Best_Combination_For_Products_And_Coupons,
    Combo_Get_Product_Page_Limit,
    Resp_Combo_Get_Product_Page_Limit,
    Combo_List_All_Products,
    Resp_Combo_List_All_Products,
    Combo_EmptyBasket,
    Resp_Combo_EmptyBasket,
    Combo_SetBasket,
    Resp_Combo_SetBasket,
    TaskConditions,
    Combo_CheckoutBasket,
    Resp_Combo_CheckoutBasket,
    CheckList_Before_TaskCompletion,
    Resp_CheckList_Before_TaskCompletion,
    ProductForCombination,
    Combo_Generate_Product_Combinations,
    Resp_Combo_Generate_Product_Combinations,
)
from .wrappers import (
    combo_find_best_combination_for_products_and_coupons,
    combo_get_product_page_limit,
    combo_list_all_products,
    combo_empty_basket,
    combo_set_basket,
    combo_checkout_basket,
    checklist_before_task_completion,
    combo_generate_product_combinations,
)

__all__ = [
    "ErrorInfo",
    "Combo_Find_Best_Combination_For_Products_And_Coupons",
    "Resp_Combo_Find_Best_Combination_For_Products_And_Coupons",
    "Combo_Get_Product_Page_Limit",
    "Resp_Combo_Get_Product_Page_Limit",
    "Combo_List_All_Products",
    "Resp_Combo_List_All_Products",
    "Combo_EmptyBasket",
    "Resp_Combo_EmptyBasket",
    "Combo_SetBasket",
    "Resp_Combo_SetBasket",
    "TaskConditions",
    "Combo_CheckoutBasket",
    "Resp_Combo_CheckoutBasket",
    "CheckList_Before_TaskCompletion",
    "Resp_CheckList_Before_TaskCompletion",
    "ProductForCombination",
    "Combo_Generate_Product_Combinations",
    "Resp_Combo_Generate_Product_Combinations",
    "combo_find_best_combination_for_products_and_coupons",
    "combo_get_product_page_limit",
    "combo_list_all_products",
    "combo_empty_basket",
    "combo_set_basket",
    "combo_checkout_basket",
    "checklist_before_task_completion",
    "combo_generate_product_combinations",
]
