"""Combo tools for Store API - high-level wrappers over erc3.store"""

from .dtos import (
    ErrorInfo,
    Find_Best_Combination_For_Products_And_Coupons,
    Resp_Find_Best_Combination_For_Products_And_Coupons,
    Get_Product_Page_Limit,
    Resp_Get_Product_Page_Limit,
    List_All_Products,
    Resp_List_All_Products,
    EmptyBasket,
    Resp_EmptyBasket,
    SetBasket,
    Resp_SetBasket,
    TaskConditions,
    ProductForCombination,
    Generate_Product_Combinations,
    Resp_Generate_Product_Combinations,
    # Task completion
    TaskCompletion,
    Resp_TaskCompletion,
    TaskSolved,
    TaskImpossible,
    NeedMoreWork,
)
from .wrappers import (
    find_best_combination_for_products_and_coupons,
    get_product_page_limit,
    list_all_products,
    empty_basket,
    set_basket,
    generate_product_combinations,
    task_completion,
)

__all__ = [
    "ErrorInfo",
    "Find_Best_Combination_For_Products_And_Coupons",
    "Resp_Find_Best_Combination_For_Products_And_Coupons",
    "Get_Product_Page_Limit",
    "Resp_Get_Product_Page_Limit",
    "List_All_Products",
    "Resp_List_All_Products",
    "EmptyBasket",
    "Resp_EmptyBasket",
    "SetBasket",
    "Resp_SetBasket",
    "TaskConditions",
    "ProductForCombination",
    "Generate_Product_Combinations",
    "Resp_Generate_Product_Combinations",
    # Task completion
    "TaskCompletion",
    "Resp_TaskCompletion",
    "TaskSolved",
    "TaskImpossible",
    "NeedMoreWork",
    "task_completion",
    # Wrapper functions
    "find_best_combination_for_products_and_coupons",
    "get_product_page_limit",
    "list_all_products",
    "empty_basket",
    "set_basket",
    "generate_product_combinations",
]
